### ISSUE TITLE
Crash on ABC stage of arithmetic cricuit synthesis

### ISSUE THREAD

**Issue by eshellko** [cliffordwolf/yosys#174]
This error happen on a relatively big arithmetic circuit optimization. I have simplified code and post few examples here. They should lead to equivalent synthesis flow. But in some cases ABC fail and in other it is not. Theoretically it could be ABC issue, but I think the problem is in data format Yosys feed into ABC.

I have attached makefile and sources ([testcase.zip](https://github.com/cliffordwolf/yosys/files/286310/testcase.zip)) to reproduce problem. My log looks like this:

> Testcase 'run-div'
> 
>  Description:
>     There is extra ',' into port list (after 'douta).
>     ABC fails with return code 134.
>     Problem is that same data passed to Yosys (with differences that should be equal like 25-20 and 25-12-4-4), and data to ABC should be the same, but sometimes error happen, and sometimes not.
> 
>  
> 
> Test 1: (1-ptr)/2
> sh: 1: 10387         (core dumped ...../yosys-abc -s -f /tmp/yosys-abc-Dt17F3/abc.script 2>&1
> ERROR: ABC: execution of command "....../yosys-abc -s -f /tmp/yosys-abc-Dt17F3/abc.script 2>&1" failed: return code 134.
> make: [run-div] Error 1 (ignore)
>  
> 
> Test 2: (1-ptr)>>1
>  
> 
> Test 3: (1+ptr)/2
>  
> 
> Test 4: (1000+ptr)/2
> sh: 1: 10465          (core dumped .../yosys-abc -s -f /tmp/yosys-abc-8IanAl/abc.script 2>&1
> ERROR: ABC: execution of command "...../yosys-abc -s -f /tmp/yosys-abc-8IanAl/abc.script 2>&1" failed: return code 134.
> make: [run-div] Error 1 (ignore)
>  
> 
> Test 5: w[5:0]=1-ptr;  w/2
>  
> 
> Test 6: w[31:0]=1-ptr;  w/2
> sh: 1: 10476         (core dumped) ...../yosys-abc -s -f /tmp/yosys-abc-i0DFof/abc.script 2>&1
> ERROR: ABC: execution of command "........../yosys-abc -s -f /tmp/yosys-abc-i0DFof/abc.script 2>&1" failed: return code 134.
> make: [run-div] Error 1 (ignore)
> 

There are 2 most interesting things:
Test 3 vs. Test 4. When 1 changed to 1000 - segfault happen.
Test 5 vs. Test 6. When result truncated and then extended - segfault happen.

**Comment by cliffordwolf** [comment]
I've been in email contact with Alan Mishchenko, the author of ABC, regarding this problem.

This seems to be a known problem with ABC's `rewrite` command with "highly redundant netlists with deep logic". Alan says this is probably not going to be fixed anytime soon because it means a lot of work in obsolete code. He suggests to simply use the newer `drw` command instead of `rewrite`.

I've now added transforming divide and modulo by a constant power of two to simpler operations in commit 11f7b8a2a1dd6e5c47e8081e4485127331fd80be. This avoids generating "highly redundant netlists" for the example you gave in the first place.
