### ISSUE TITLE
include license texts

### ISSUE THREAD

**Issue by brouhaha** [cliffordwolf/yosys#263]
In the Fedora package review, it has been pointed out to me that Fedora packaging policy requires that I request upstream to include files with the full text of applicable licenses. This would appear to include ISC, MIT, GPLv2, GPLv3, and LGPLv2.

**Comment by cliffordwolf** [comment]
The bulk of Yosys is ISC. Some parts are public domain (kernel/hashlib.h, libs/sha1/, libs/bigint/). libs/minisat/ is under MIT (which is permissive and compatible with ISC).

ABC is a stand-alone binary with it's own set of licences. At least in Debian ABC is its own package.

No part of Yosys is GPLv2, GPLv3, or LGPLv2. Some of the test cases are (because they are copied from designs that are using those licences), but this should have no effect on the licence status of Yosys itself.
