### ISSUE TITLE
Maybe an issue in the equivalence check

### ISSUE THREAD

**Issue by rafaeltp** [cliffordwolf/yosys#341]
I was playing with the equivalency check and came across a weird behavior. 
I think it is a bug, but maybe I am missing something.

My script is 
```
equiv_make gold top_w equiv
 hierarchy -top equiv
 opt -purge
 equiv_simple
 equiv_status -assert
```

and the minimal code to get the issue that I was able to generate 

```
module gold(input i1, input i2, output o2, output o1);
 wire _1_;
 assign o2 = i1 & i2;
 assign _1_ = i1 | i2;
 assign o1 = _1_ & o2;
endmodule

module top_r( i1, i2, o1, o2 );
  input i1, i2;
  output o1, o2;
  wire w4;
  assign o2 = (i2 & i1);
  assign w4 = ((i2 && i1) | (i2) | (i1));
  assign o1 = ((w4 & o2));
endmodule

module top_w( i1, i2, o1, o2 );
  input i1, i2;
  output o1, o2;
  wire w4;
  assign o2 = (i2 & i1);
  assign w4 = ((i2 & i1) | (i2) | (i1));
  assign o1 = ((w4 & o2));
endmodule
```

The issue is with top_w, top_r uses && instead of & in the assignment of w4, but both expression should simplify to `i2 + i1`.

**Comment by cliffordwolf** [comment]
Thanks for reporting this issue. And thanks for providing such an excellent test case. Fixed in 3bbac5c.

The problem was a performance optimization that in this case caused the tool to try to prove that `o1_gold == o1_gate` while treating `o2` like a primary input, i.e. the tool ignored that the value of `o2` depends on `i1` and `i2`. This caused the prove for `o1` to fail, depending on the amount of optimization that happened on the design. (For the coarse-grain optimizer the expressions `i2 && i1` and `i2 & i1` are distinct and are not merged. Because of this, the equivalence checker was given slightly different input circuits when `top_r` or `top_w` is used.) This optimization is now disabled by default and can be enabled by running `equiv_simple` with the new `-short` option.
