### ISSUE TITLE
D flip flop $_DFFSR_NPP_ not defined for ICE40

### ISSUE THREAD

**Issue by ironsteel** [cliffordwolf/yosys#404]
First off I'm a total beginner in the fpga world but I was intrigued when I found about the FOSS toolchain. Thank you for your great work.

The design that I'm trying to synthesize is the sump2 logic analyzer for the ICOBoard but I get the following error from arachne-pnr:

    top.blif:11335: fatal error: unknown model `$_DFFSR_NPP_'

After searching thought the sources  I found that $_DFFSR_NPP_  flip flop is not present for  ICE40 devices.

Is there any limitation for this module to not be present for ICE40 devices?

**Comment by cliffordwolf** [comment]
> Is there any limitation for this module to not be present for ICE40 devices?

I think this is a question you have to direct to Lattice (or SiliconBlue), not me. I did not design the iCE40 devices. But it is quite common for FPGAs to not support SR flip-flops. Most of them don't.

(In some cases the vendor tools output a warning message that the developer ignores because he doesn't understand it and the tools implement the SR-FF as a FF with async reset, a second FF with async set, a latch that remembers if set or reset was last used, and a MUX that select one of the two FFs based on the latch output. This is obviously horrible and nobody actually wants a horrific abomination like that in their synthesized design.)

> The design that I'm trying to synthesize is the sump2 logic analyzer

Then this is a sign that the HDL code for sump is badly broken and needs to be fixed.
