### ISSUE TITLE
Support for flip-flops with async clear and preset for iCE40 devices

### ISSUE THREAD

**Issue by set-soft** [cliffordwolf/yosys#470]
While modeling an asynchronous FIFO according to "Simulation and Synthesis Techniques for Asynchronous FIFO Design with Asynchronous Pointer Comparisons" by Clifford E. Cummings and Peter Alfke SNUG 2002, I had to describe a DFF with async CLR and PRE, like this:

```
module ff_clr_pre
  (
   input  clk,
   input  clr,
   input  pre,
   input  d,
   output reg q);

 always @(posedge clk or posedge clr or posedge pre) 
 begin : do_ff
  if (clr)
     q <= 1'b0;
  else if (pre)
     q <= 1'b1;
  else
     q <= d;
 end // d0_ff
 endmodule // ff_clr_pre
```
When I run:

> yoysys  -q -p "synth_ice40 -blif test.blif" test.v

I get a warning about complex reset:

> Warning: Complex async reset for dff `\q'.

And the BLIF output contains an unmaped $\_DFFSR_PPP\_
I don't know how to add mapping rules. One solution to this problem is to use 2 flip-flops. The first flip-flop implements the async preset and the normal D/Q behavior. The second flip-flop is used to generate the async clear. This flip-flop has D tied to Vcc and has CLR. The modeled output is the and between both FFs:

```
module DFF_ASR
  (
   input  d_i,
   output q_o,
   input  clk_i,
   input  clr_i,
   input  pre_i);
// Simpler FF, only preset
reg q;
always @(posedge clk_i or posedge pre_i)
begin : do_ff
  if (pre_i)
     q <= 1'b1;
  else
     q <= d_i;
end // do_ff
// Another FF for clear
reg q_clr;
always @(posedge clk_i or posedge clr_i)
begin : do_clr
  if (clr_i)
     q_clr <= 1'b0;
  else
     q_clr <= 1'b1;
end // do_clr
// Output is conditioned by the clear FF
assign q_o=q & q_clr;
endmodule // DFF_ASR
```
The yosys version I'm using is:

Yosys 0.7+207 (git sha1 ea805af6, gcc 6.3.0-18 -O2 -fdebug-prefix-map=/home/salvador/0Data/IceStorm/Yosys/Debian-git/yosys=. -fstack-p
rotector-strong -fPIC -Os)

**Comment by cliffordwolf** [comment]
iCE40 has no hardware primitive for FFs with async set and clear. A mapping rule would need to substitute it with a circuit that implements this from other primitives.

But your DFF_ASR solution is incorrect: If there is a clr_i pulse followed by a pre_i pulse then a DFF with async CLR and PRE should have a set output. But your solution will have a cleared output.

The correct way to do that would require an S/R latch that remembers if the last async event was CLR or PRE. That latch would then control a MUX that selects one of the two FF outputs.

However, iCE40 also has no hardware primitive for latches. So the latch must be built from a logic feedback loop. This is not only a very ugly circuit, adding logic loops also breaks topological timing analysis. Therefore there is no automatic mapping rule for storage elements like that: The resulting circuit would be so ugly, if you really want it you have to explicitly build it yourself.

In most cases circuits with FFs with async set and clear are broken anyways because they assume glitch free logic synthesis for the signals driving the set and clear outputs. But generally it can not be assumed that the output from logic synthesis is guaranteed to be glitch free.
